# Generated by Django 2.1.5 on 2024-04-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountTransaction',
            new_name='Transaction',
        ),
    ]
